Problems pagination
Judge-Girl/Judge-Girl-Web pull request #127
Opened 2021-11-30 07:24 UTC by sh910913

This development use ng-bootstrap plugin.

2021-12-02 05:56 UTC, sh910913 commented
因爲後端API沒調整，所以資料就沒有更新。

https://user-images.githubusercontent.com/29350642/144365913-6cc3f8d7-27a1-4e78-b838-dd0478a1d78c.mov

2021-12-06 17:29 UTC, Wally5077 requested changes
Review done

2021-12-06 17:29 UTC, Wally5077 commented on src/app/pages/problems/problem-list.component.html
> +    <ngb-pagination (pageChange)="getPageTestData($event)" [collectionSize]="pageProps.totalRecords" [pageSize]="pageProps.pageSize" [(page)]="pageProps.page" [maxSize]="5" [rotate]="true" [ellipses]
Since we used ```Pagination```, you need to amend this part.

2021-12-06 17:29 UTC, Wally5077 commented on src/app/pages/problems/problem-list.component.ts
> +  pageProps: PageProps;
Change `problemPagination: Pagination<ProblemItem>;` and remove `pageProps`.

2021-12-06 17:29 UTC, Wally5077 commented on src/app/pages/problems/problem-list.component.ts
> +    this.pageProps = new PageProps();
ditto

2021-12-06 17:29 UTC, Wally5077 commented on src/app/pages/problems/problem-list.component.ts
> +  getPageTestData(pageNumber: number) {
Rename this method to `getPagination`.

2021-12-07 07:08 UTC, sh910913 commented
調整樣式
https://user-images.githubusercontent.com/29350642/144982679-5e455b72-84aa-4145-bef5-7139977e42d5.mov

2021-12-07 07:09 UTC, sh910913 commented
調整樣式

https://user-images.githubusercontent.com/29350642/144982849-ae716c99-3f96-440d-9eec-86a7cb4db6be.mov

2021-12-14 16:23 UTC, Wally5077 requested changes
Review done

2021-12-14 16:23 UTC, Wally5077 commented on src/app/commons/widgets/pagination/pagination.component.ts
> +        if (this.pagination === undefined) {
`!this.pagination`

2021-12-14 16:23 UTC, Wally5077 commented on src/app/pages/problems/problem-list.component.ts
> +
Remove this empty line.

2021-12-14 16:26 UTC, Wally5077 approved these changes
LGTM

2022-01-06 15:21 UTC, Chaoyuuu approved these changes
LGTM

2022-01-06 15:21 UTC, merged