[WIP] Add shadow to question banner
Judge-Girl/Judge-Girl-Web pull request #52
Opened 2021-04-26 12:41 UTC by edisonhello

2021-04-26 14:06 UTC, Johnny850807 requested changes
Review done

2021-04-26 14:06 UTC, Johnny850807 commented on src/app/exam/question-banner/question-banner.component.ts
> +  updateExamInformation(student: Student) {
rename `updateExamProgressOverview`

2021-04-27 15:35 UTC, edisonhello commented on src/app/exam/question-banner/question-banner.component.ts
> +  updateExamInformation(student: Student) {
Fixed.

2021-04-30 05:16 UTC, Johnny850807 approved these changes
LGTM

2021-04-30 05:17 UTC, Chaoyuuu approved these changes
LGTM

2021-04-30 07:38 UTC, merged